package dev.sha256.ultrahub.cooldown;

public enum CooldownType {
    LOCK_BREAK, BLOCK_PLACE, BLOCK_INTERACT, ITEM_DROP, ITEM_PICKUP, PLAYER_PVP, DOUBLE_JUMP, LAUNCHPAD, BLOCK_BREAK, ENDERBUTT, PLAYER_HIDER
}
