package dev.sha256.ultrahub.module;

public enum ModuleType {

    DOUBLE_JUMP,
    VANISH,
    LOBBY, WORLD_PROTECT, LAUNCHPAD, PLAYER_LISTENER, PLAYER_OFFHAND_LISTENER, HOTBAR_ITEMS, SCOREBOARD, TABLIST, ANTI_SWEAR, ANNOUNCEMENTS, COMMAND_BLOCK, CUSTOM_COMMANDS, CHAT_LOCK, ANTI_WOL

}
